spring.datasource.url=${riskregisterhq_java_db_url:jdbc:mysql://127.0.0.1:3306/riskregister?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&connectTimeout=10000&socketTimeout=10000}
spring.datasource.username=${riskregisterhq_java_db_username}
spring.datasource.password=${riskregisterhq_java_db_password}
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8;
spring.datasource.tomcat.connection-properties=useUnicode=true;characterEncoding=utf-8;

# Additional MySQL connection properties
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=${riskregisterhq_java_hibernate_ddl_auto:update}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=180d
server.servlet.session.timeout=180d
server.servlet.session.cookie.max-age=180d
server.session.persistent=true
server.servlet.session.persistent=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

passwordless.email.from=${riskregisterhq_email_from}
spring.mail.host=${riskregisterhq_java_mail_host}
spring.mail.port=${riskregisterhq_java_mail_port:587}
spring.mail.username=${riskregisterhq_java_email_username}
spring.mail.password=${riskregisterhq_java_email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=${riskregisterhq_java_mail_port:587}
spring.mail.properties.mail.debug=${riskregisterhq_java_mail_debug:false}

host.url=${riskregisterhq_java_host_url:http://localhost:8080}
server.port=${riskregisterhq_java_server_port:8080}

